package com.example.model;


import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * Created by liveangel on 2016-10-17.
 */
@Entity
@Table(name = "customer")
public class Customer {
    public void setId(long id) {
        this.id = id;
    }

    // ==============
    // PRIVATE FIELDS
    // ==============
    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    // The user email
//    @NotNull
    private String email;
    // The user name
    private String name;

    private String address;
//    @Column(nullable = false)
    private String firstName;
    private String lastName;

    // ==============
    // PUBLIC METHODS
    // ==============
    protected Customer() {}
    public Customer(String firstName, String lastName,String name, String email, String address) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.name = name;
        this.address = address;
    }
    @Override
    public String toString() {
        return String.format(
                "Customer[id=%d, firstName='%s', lastName='%s']",
                id, firstName, lastName);
    }
    public long getId(){
        return this.id;
    }
    // Getter and setter methods
    // ...
} // class User
